version: "3.8"

services:

  model-consumer:
    build:
      context: ./model-consumer
    image: model-consumer
    container_name: model-consumer
    environment:
      - MONGO_URI=mongodb://$MONGO_USER:$MONGO_PASSWORD@mongo:27017
      - MODEL_SERVING_HOST=model-serving
      - MODEL_SERVING_PORT=8080  
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    env_file:
      - .env

  model-serving:
    build:
      context: ./model-serving
    image: model-serving
    container_name: model-serving
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
